- pkg:maven/io.prometheus.jmx/jmx_prometheus_common@0.19.0
- pkg:maven/io.prometheus.jmx/jmx_prometheus_common@0.19.0?classifier=sources
- pkg:maven/io.prometheus.jmx/jmx_prometheus_common@0.20.0
- pkg:maven/io.prometheus.jmx/jmx_prometheus_common@0.20.0?classifier=sources
- pkg:maven/io.prometheus.jmx/jmx_prometheus_common@1.0.0
- pkg:maven/io.prometheus.jmx/jmx_prometheus_common@1.0.0?classifier=sources
- pkg:maven/io.prometheus.jmx/jmx_prometheus_common@1.0.1
- pkg:maven/io.prometheus.jmx/jmx_prometheus_common@1.0.1?classifier=sources
