- pkg:maven/org.apache.skywalking/telemetry-prometheus@6.0.0-GA
- pkg:maven/org.apache.skywalking/telemetry-prometheus@6.1.0
- pkg:maven/org.apache.skywalking/telemetry-prometheus@6.2.0
- pkg:maven/org.apache.skywalking/telemetry-prometheus@6.3.0
- pkg:maven/org.apache.skywalking/telemetry-prometheus@6.4.0
- pkg:maven/org.apache.skywalking/telemetry-prometheus@6.5.0
- pkg:maven/org.apache.skywalking/telemetry-prometheus@6.6.0
