- pkg:maven/ai.djl.serving/prometheus@0.27.0
- pkg:maven/ai.djl.serving/prometheus@0.27.0?classifier=sources
- pkg:maven/ai.djl.serving/prometheus@0.28.0
- pkg:maven/ai.djl.serving/prometheus@0.28.0?classifier=sources
- pkg:maven/ai.djl.serving/prometheus@0.34.0
- pkg:maven/ai.djl.serving/prometheus@0.34.0?classifier=sources
