- pkg:maven/dk.kvalitetsit/spring-prometheus-app-info@1.2.0
- pkg:maven/dk.kvalitetsit/spring-prometheus-app-info@1.2.0?classifier=sources
- pkg:maven/dk.kvalitetsit/spring-prometheus-app-info@2.0.1
- pkg:maven/dk.kvalitetsit/spring-prometheus-app-info@2.0.1?classifier=sources
- pkg:maven/dk.kvalitetsit/spring-prometheus-app-info@2.0.2
- pkg:maven/dk.kvalitetsit/spring-prometheus-app-info@2.0.2?classifier=sources
- pkg:maven/dk.kvalitetsit/spring-prometheus-app-info@2.0.3
- pkg:maven/dk.kvalitetsit/spring-prometheus-app-info@2.0.3?classifier=sources
- pkg:maven/dk.kvalitetsit/spring-prometheus-app-info@3.0.0?classifier=sources
- pkg:maven/dk.kvalitetsit/spring-prometheus-app-info@3.0.1?classifier=sources
