- pkg:maven/com.dorkbox/Config@1.0?classifier=sources
- pkg:maven/com.dorkbox/Config@1.1?classifier=sources
- pkg:maven/com.dorkbox/Config@1.2?classifier=sources
- pkg:maven/com.dorkbox/Config@1.3?classifier=sources
- pkg:maven/com.dorkbox/Config@1.4?classifier=sources
- pkg:maven/com.dorkbox/Config@1.5?classifier=sources
- pkg:maven/com.dorkbox/Config@1.6?classifier=sources
- pkg:maven/com.dorkbox/Config@1.7?classifier=sources
- pkg:maven/com.dorkbox/Config@1.9?classifier=sources
- pkg:maven/com.dorkbox/Config@2.0?classifier=sources
- pkg:maven/com.dorkbox/Config@2.1?classifier=sources
- pkg:maven/com.dorkbox/Config@2.2?classifier=sources
- pkg:maven/com.dorkbox/Config@2.3?classifier=sources
- pkg:maven/com.dorkbox/Config@2.4?classifier=sources
- pkg:maven/com.dorkbox/Config@2.5?classifier=sources
- pkg:maven/com.dorkbox/Config@2.6?classifier=sources
- pkg:maven/com.dorkbox/Config@2.7?classifier=sources
- pkg:maven/com.dorkbox/Config@2.8?classifier=sources
