- pkg:maven/com.dorkbox/Config@1.0?classifier=sources
- pkg:maven/com.dorkbox/Config@1.1?classifier=sources
- pkg:maven/com.dorkbox/Config@1.2?classifier=sources
- pkg:maven/com.dorkbox/Config@1.3?classifier=sources
- pkg:maven/com.dorkbox/Config@1.4?classifier=sources
- pkg:maven/com.dorkbox/Config@1.5?classifier=sources
- pkg:maven/com.dorkbox/Config@1.6?classifier=sources
