- pkg:maven/com.netflix.netflixoss.test.travisci/app@0.1.0?classifier=sources
- pkg:maven/com.netflix.netflixoss.test.travisci/app@0.2.0?classifier=sources
- pkg:maven/com.netflix.netflixoss.test.travisci/app@0.3.0?classifier=sources
- pkg:maven/com.netflix.netflixoss.test.travisci/app@0.6.0?classifier=sources
- pkg:maven/com.netflix.netflixoss.test.travisci/app@9999.0.1?classifier=sources
- pkg:maven/com.netflix.netflixoss.test.travisci/app@9999.0.2?classifier=sources
