- pkg:maven/us.oyanglul/finagle-prometheus_2.12@0.1.0
- pkg:maven/us.oyanglul/finagle-prometheus_2.12@0.1.0?classifier=sources
- pkg:maven/us.oyanglul/finagle-prometheus_2.12@0.2.0
- pkg:maven/us.oyanglul/finagle-prometheus_2.12@0.2.0?classifier=sources
