- pkg:maven/com.github.shootmoon/xmlconfigmapper-integrationtest@0.1.2
- pkg:maven/com.github.shootmoon/xmlconfigmapper-integrationtest@0.2.0
- pkg:maven/com.github.shootmoon/xmlconfigmapper-integrationtest@0.2.1
