- pkg:maven/be.ceau/chart@0.9
- pkg:maven/be.ceau/chart@0.9?classifier=sources
- pkg:maven/be.ceau/chart@2.0.0
- pkg:maven/be.ceau/chart@2.0.0?classifier=sources
- pkg:maven/be.ceau/chart@2.0.1
- pkg:maven/be.ceau/chart@2.0.1?classifier=sources
- pkg:maven/be.ceau/chart@2.2.0
- pkg:maven/be.ceau/chart@2.2.0?classifier=sources
- pkg:maven/be.ceau/chart@2.2.1
- pkg:maven/be.ceau/chart@2.2.1?classifier=sources
- pkg:maven/be.ceau/chart@2.3.0
- pkg:maven/be.ceau/chart@2.3.0?classifier=sources
- pkg:maven/be.ceau/chart@2.3.1
- pkg:maven/be.ceau/chart@2.3.1?classifier=sources
- pkg:maven/be.ceau/chart@2.4.0
- pkg:maven/be.ceau/chart@2.4.0?classifier=sources
- pkg:maven/be.ceau/chart@2.5.0
- pkg:maven/be.ceau/chart@2.5.0?classifier=sources
